/Users/timotejkralik/Documents/Osobne/school/DP_pose_estimation/dp_vitpose_prototype/lib/python3.11/site-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 10 worker processes in total. Our suggested max number of worker in current system is 8 (`cpuset` is not taken into account), which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
submitit ERROR (2023-10-14 17:35:45,260) - Submitted job triggered an exception
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/timotejkralik/Documents/Osobne/school/DP_pose_estimation/dp_vitpose_prototype/lib/python3.11/site-packages/submitit/core/_submit.py", line 11, in <module>
    submitit_main()
  File "/Users/timotejkralik/Documents/Osobne/school/DP_pose_estimation/dp_vitpose_prototype/lib/python3.11/site-packages/submitit/core/submission.py", line 76, in submitit_main
    process_job(args.folder)
  File "/Users/timotejkralik/Documents/Osobne/school/DP_pose_estimation/dp_vitpose_prototype/lib/python3.11/site-packages/submitit/core/submission.py", line 69, in process_job
    raise error
  File "/Users/timotejkralik/Documents/Osobne/school/DP_pose_estimation/dp_vitpose_prototype/lib/python3.11/site-packages/submitit/core/submission.py", line 55, in process_job
    result = delayed.result()
             ^^^^^^^^^^^^^^^^
  File "/Users/timotejkralik/Documents/Osobne/school/DP_pose_estimation/dp_vitpose_prototype/lib/python3.11/site-packages/submitit/core/utils.py", line 133, in result
    self._result = self.function(*self.args, **self.kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timotejkralik/Documents/Osobne/school/DP_pose_estimation/pose_estimation_vitpose/mae/submitit_pretrain.py", line 72, in __call__
    trainer.main(self.args)
  File "/Users/timotejkralik/Documents/Osobne/school/DP_pose_estimation/pose_estimation_vitpose/mae/main_pretrain.py", line 156, in main
    model = models_mae.__dict__[args.model](norm_pix_loss=args.norm_pix_loss)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timotejkralik/Documents/Osobne/school/DP_pose_estimation/pose_estimation_vitpose/mae/models_mae.py", line 224, in mae_vit_base_patch16_dec512d8b
    model = MaskedAutoencoderViT(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timotejkralik/Documents/Osobne/school/DP_pose_estimation/pose_estimation_vitpose/mae/models_mae.py", line 63, in __init__
    self.initialize_weights()
  File "/Users/timotejkralik/Documents/Osobne/school/DP_pose_estimation/pose_estimation_vitpose/mae/models_mae.py", line 68, in initialize_weights
    pos_embed = get_2d_sincos_pos_embed(self.pos_embed.shape[-1], int(self.patch_embed.num_patches**.5), cls_token=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timotejkralik/Documents/Osobne/school/DP_pose_estimation/pose_estimation_vitpose/mae/util/pos_embed.py", line 32, in get_2d_sincos_pos_embed
    pos_embed = get_2d_sincos_pos_embed_from_grid(embed_dim, grid)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timotejkralik/Documents/Osobne/school/DP_pose_estimation/pose_estimation_vitpose/mae/util/pos_embed.py", line 42, in get_2d_sincos_pos_embed_from_grid
    emb_h = get_1d_sincos_pos_embed_from_grid(embed_dim // 2, grid[0])  # (H*W, D/2)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timotejkralik/Documents/Osobne/school/DP_pose_estimation/pose_estimation_vitpose/mae/util/pos_embed.py", line 56, in get_1d_sincos_pos_embed_from_grid
    omega = np.arange(embed_dim // 2, dtype=np.float)
                                            ^^^^^^^^
  File "/Users/timotejkralik/Documents/Osobne/school/DP_pose_estimation/dp_vitpose_prototype/lib/python3.11/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?
